// <copyright file="WeatherType.cs" company="Principal33 Solutions">
// Copyright (c) Principal33 Solutions. All rights reserved.
// </copyright>

namespace HelloWorldWeb.Models
{
    /// <summary>
    /// All weather description tipes from API.
    /// </summary>
    public enum WeatherType
    {
        Freezing,
        Bracing,
        Chilly,
        Cool,
        Mild,
        Warm,
        Balmy,
        Hot,
        Sweltering,
        Scorching,
        FewClouds,
        LighRain,
        BrokenClouds,
        ThunderstormWithLightRain,
        ThunderstormWithRain,
        ThunderstormWithHeavyRain,
        LighThunderstorm,
        Thunderstorm,
        HeavyThunderstorm,
        RaggedThunderstorm,
        ThunderstormWithLightDrizzle,
        ThunderstormWithDrizzle,
        ThunderstormWithHeavyDrizzle,
        LightIntensityDrizzle,
        Drizzle,
        HeavyIntensityDrizzle,
        LightIntensityDrizzleRain,
        DrizzleRain,
        HeavyIntensityDrizzleRain,
        ShowerRainAndDrizzle,
        HeavyShowerRainAndDrizzle,
        ShowerDrizzle,
        LightRain,
        ModerateRain,
        HeavyIntensityRain,
        VeryHeavyRain,
        ExtremeRain,
        FreezingRain,
        LightIntensityShowerRain,
        ShowerRain,
        HeavyIntensityShowerRain,
        RaggedShowerRain,
        LightSnow,
        HeavySnow,
        Sleet,
        LightShowerSleet,
        ShowerSleet,
        LightRainAndSnow,
        RainAndSnow,
        LightShowerSnow,
        ShowerSnow,
        HeavyShowerSnow,
        Mist,
        Haze,
        SandDustWhirls,
        Fog,
        Sand,
        Dust,
        VolcanicAsh,
        Squalls,
        Tornado,
        ClearSky,
        ScatteredClouds,
        OvercastClouds,
    }
}